gitlab-server:
  ports:
  - 22:22/tcp
  - 80:80/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:8.12.1-ce.0
  volumes_from:
  - gitlab-data

gitlab-migrate:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/bash
  command:
  - -c "/bin/cp -Rp /etc/gitlab/* /vol/etc/gitlab/ && /bin/cp -Rp /var/opt/gitlab/* /vol/var/opt/gitlab/ && /bin/cp -Rp /var/log/gitlab/* /vol/var/log/gitlab/"
  hostname: gitvolumes
  image: gitlab/gitlab-ce:8.12.1-ce.0
  volumes:
  - gitlab-etc:/vol/etc/gitlab
  - gitlab-log:/vol/var/log/gitlab
  - gitlab-opt:/vol/var/opt/gitlab
   volumes_from:
  - gitlab-data

